# -*- coding: utf-8 -*-
"""Copy of now_i_am_life_maker_of_the_photos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_i3kS0vvs3LUPegDdv_ZMhVqz6cd4-4f

**Set Up the Environment:**

Ensure that the Colab notebook is configured to use a GPU.

Install the necessary packages:
"""

"""!pip install super-image
!pip install huggingface_hub==0.25.1"""

"""**Import Required Libraries:**

Import the DrlnModel and ImageLoader from the super_image library, along with other necessary modules:
"""

from super_image import MsrnModel, ImageLoader
from PIL import Image
import requests
import torch

"""**Load the Image:**

Load the image you wish to enhance. You can use a URL or upload an image directly:
"""

from google.colab import files
from PIL import Image
import io

# Upload the file
uploaded = files.upload()

# Iterate over the uploaded files
for filename, filecontent in uploaded.items():
    # Save the uploaded file to the local filesystem
    with open(filename, 'wb') as f:
        f.write(filecontent)

    # Open the image using PIL
    image = Image.open(filename)
    # Display the image
    image.show()

"""**Initialize the DRLN Model:**

Load the pre-trained DRLN model for 4x upscaling:
"""

model = MsrnModel.from_pretrained('eugenesiow/msrn', scale=4)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

"""**Prepare the Image for Upscaling:**

Convert the image to the appropriate format for the model:


"""

inputs = ImageLoader.load_image(image).to(device)

"""**Perform Upscaling:**

Use the model to upscale the image:
"""

with torch.no_grad():
    preds = model(inputs)

"""**Save and Display the Enhanced Image:**

Save the upscaled image and display it:
"""

output_path = './enhanced_image.png'
ImageLoader.save_image(preds, output_path)

# Display the image
from IPython.display import Image as IPImage
IPImage(output_path)
